#!/bin/bash

if (( $# < 2 )); then
    echo "ERROR: Not enough arguments" >&2
    echo "USAGE `basename $0` <dvd|cd> PAYLOAD..." >&2
fi

format=$1; shift

if [[ $(file $1) =~ "ISO" ]]; then
    iso=$1
else
    if [ $# -eq 1 -a -d "$1" ]; then
        dir=$1
    else
        dir=$(mktemp -d)
        cp -r $@ ${dir}
    fi
    echo "> Creating iso"
    iso=$(mktemp)
    set -x
    mkisofs -V ${1} -J -r -o ${iso} ${dir} || exit 1
fi

echo "> Burning to disc"
case ${format} in
dvd) growisofs -dvd-compat -Z /dev/sr0=${iso} ;;
cd)  cdrecord -v -sao dev=/dev/sr0 ${iso} ;;
esac

eject
