#!/bin/sh

if [ $# -lt 2 ]; then
    echo "ERROR: Not enough arguments" >&2
    echo "USAGE `basename $0` <dvd|cd> DIR [LABEL]" >&2
fi

format=$1
dir=$2
[ $# -gt 2 ] && lbl=$3 || lbl=`basename $2`

mkisofs -V ${lbl} -J -r -o /tmp/${lbl}.iso ${dir} || exit 1

case ${format} in
dvd) growisofs -dvd-compat -Z /dev/sr0=/tmp/${lbl}.iso ;;
cd) cdrecord -v -sao dev=/dev/sr0 /tmp/${lbl}.iso ;;
esac

eject
