#!/bin/bash

if (( $# < 2 )); then
    echo "USAGE ${0##*/} <dvd|cd> FILES...|ISO" >&2
    exit 1
fi

format=$1; shift

if [[ ! $(file $1) =~ "ISO" ]]; then
    echo ":: Creating iso"
    iso=$(mktemp)
    trap "rm -rf ${iso}" EXIT
    mkisofs -V ${1} -J -r -o ${iso} $@ || exit 2
fi

echo ":: Burning ${format}"
case ${format} in
cd)  cdrecord -v -sao dev=/dev/sr0 ${iso:-$1} ;;
dvd) growisofs -dvd-compat -Z /dev/sr0=${iso:-$1} ;;
*) exit 3 ;;
esac

eject
