#!/bin/sh

# USAGE: [b] [%]IMG

[ "$1" == "b" ] && {
    build=true
    shift
}

img=${1/\%/hokiegeek\/}; shift

${build:-false} \
    && docker build $@ ${img} . \
    || docker run -it --rm ${img} $@
