#!/bin/bash

threshold=1
list="$HOME/.dmenu_run_mfu"
[ ! -f "${list}" ] && touch "${list}"

dmenu_path | awk '
$0 ~ /^ *$/ { next }
NR == FNR && NF > 1 {
    if ($1 > '${threshold}') {
        mfu[$2] = $1
        print $2
    }
    next
}
!($0 in mfu) {
    print
}
' <(sort -hr ${list}) - | dmenu "$@" | awk '
FILENAME == "-" {
    sel = $0
    sel_cmd = $1
    next
}
$0 !~ /^ *$/ {
    mfu[$2] = $1
    if (sel_cmd == $2) {
        mfu[$2]++
    }
}
END {
    if (length(sel_cmd) > 0 && sel_cmd !~ "^ *$") {
        if (!(sel_cmd in mfu)) {
            mfu[sel_cmd] = 1
        }
        for (cmd in mfu) {
            print mfu[cmd] " " cmd > FILENAME
        }
    }
    print sel
}
' - ${list} | ${SHELL:-"/bin/sh"} &
