#!/bin/sh

if [ $# -le 0 ]; then
    while read i; do
        echo ${i}
    done
else
    echo "$@"
fi | sed -e 's/ /\n/g' \
    | while read a; do
        which $a &>/dev/null && exec echo $a
    done
