#!/bin/sh

if [ $# -gt 0 -a "$1" == "--help" ]; then
    echo "USAGE: git sublog [--help] <revision>"
    exit 1
fi
[ $# -gt 0 ] && rev="$1" || rev="HEAD~1"

for x in `git diff ${rev}.. | awk '$1 ~ /^diff/ || $1 ~ /^-Subproject/ { sub("^b/", "", $NF); print $NF }' | sed '$!N;s/\n/:/'`; do
    p=`echo ${x} | cut -d: -f1`
    r=`echo ${x} | cut -d: -f2`
    if [ -d "${p}" ]; then
        echo -e "\033[35mSubmodule: ${p}"
        echo -e "\033[35mRevision:  ${r}"
        echo -en '\033[0m'
        pushd ${p} 2>&1 >/dev/null
        git --no-pager log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan)<%an>%Creset' ${r}..
        popd 2>&1 >/dev/null
        echo -e "\n"
    fi
done | less -R
