#!/bin/sh

for arg in "$@"; do
    [ "$arg" == "--color=never" -o "$arg" == "--no-color" ]  && useColor=false
done

# ${useColor:-true} && 

cmd="git --no-pager grep $@"
${cmd} && \
git submodule --quiet foreach --recursive "${cmd} | \
awk '{ printf(\"%s/%s\n\", \"'\$path'\", \$0) }' || :"
