#!/bin/bash

revs=()
while (( $# > 0 )); do
    case $1 in
        --help) echo "USAGE: git sublog [--help] [START_REVISION] [END_REVISION]" >&2 ;;
        *) revs+=($1) ;;
    esac
    shift
done

git diff ${revs[0]:-"HEAD~1"}..${revs[1]:-"HEAD"} | \
    awk '
    $1 ~ /diff/ {
        sub("b/", "", $NF)
        submodule=$NF
    }
    $1 ~ /-Subproject/ { oldrev=$NF }
    $1 ~ /+Subproject/ { printf("%s %s %s\n", submodule, oldrev, $NF) }
    ' | while read submodule rev1 rev2; do
            printf "\033[35mSubmodule: %s\nRevision:  %s..%s\n\033[0m" ${submodule} ${rev1} ${rev2}
            git --no-pager --git-dir=${submodule}/.git \
                log \
                --graph \
                --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan)<%an>%Creset' \
                ${rev1}..${rev2}
            echo -e "\n"
        done
