#!/bin/sh

git branch -a | awk '
{
    sub(/ *remotes\/|^* /, "")
    cmd = sprintf("git log -1 --pretty=format:\"%%Cgreen%%ci %%Cblue%%cr%%Creset\" %s", $1)
    cmd |& getline ds
    close(cmd)
    printf("%-63s %s\n", ds, $0)
}
' | sort $1
