#!/bin/bash

[[ $@ =~ --?h(elp)? ]] && {
    echo "USAGE: git sublog [-h] START_REVISION[[..][END_REVISION]]"
    exit
}

git diff $@ | \
    awk '
    BEGIN { logfmt="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan)<%an>%Creset" }
    $1 ~ /diff/ {
        sub("b/", "", $NF)
        submodule=$NF
    }
    $1 ~ /-Subproject/ { oldrev=$NF }
    $1 ~ /+Subproject/ {
        printf("\033[35mSubmodule: %s\nRevision:  %s..%s\n\033[0m", submodule, oldrev, $NF)
        system(sprintf("git --no-pager --git-dir=%s/.git log --graph --pretty=format:\"%s\" %s..%s", submodule, logfmt, oldrev, $NF))
        printf("\n\n")
    }
    '
