#!/bin/sh

[ "$1" == "--html" ] && {
    html=true
    shift
}

tmp=$(mktemp)

go test -covermode=count -coverprofile=${tmp} $@
go tool cover -func=${tmp}
${html:-false} && go tool cover -html=${tmp}
