#!/bin/bash
xdotool key super+ctrl+t
st -g 6x1-0-0 -e watch -t "${1:-"hrs"} list | \
    sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g' | \
    awk '/ONGOING/ { print \$2 }'" &
sleep 0.25s
xdotool key super+ctrl+t
