#!/bin/bash

[[ ! -f ${mntpoint=/mnt/kindle} ]] && sudo mkdir -p ${mntpoint}
echo "Mounting Kindle"
sudo mount $1 ${mntpoint}
echo "Copying file(s)"
sudo cp -v ${@:2} ${mntpoint}
sync
echo "Unmounting Kindle"
sudo umount ${mntpoint}
