#!/bin/bash

declare -A keymap
# keymap["monb-d"]="-e XF86_Calculator"
keymap["monb-d"]="-e XF86_MonBrightnessDown"
keymap["monb-u"]="-e XF86_MonBrightnessUp"

(( $# == 0 )) && {
    echo "USAGE: ${0##*/} [-sS] [-cC] [-aA] [-uU] [keysym_shorthand]"
    man xkev | sed '17,36!d;/^$/d;/_Meta_/d'

    for key in ${!keymap[@]}; do
        printf "\t%s     %s\n" $key ${keymap[$key]/-e /}
    done
    exit 1
} >&2

exec xkev $(for arg in $@; do echo "${keymap[${arg}]:-${arg}}"; done)
