#!/bin/bash

if [ "$1" = "--cron" ]; then
    crontab <(
        crontab -l 2>/dev/null | grep -v "${0##*/}"
        printf '*/4 * * * * %s %s >/dev/null\n' "$(cd ${0%/*}; pwd)/${0##*/}" $HOME/Dropbox/ip
        )
    crontab -l
else
    wget -q -O /dev/stdout http://checkip.dyndns.org/ | cut -d : -f 2- | cut -d \< -f -1 | awk '{ print $1 }' > $1
fi
