#!/bin/bash

if [ "$2" = "--cron" ]; then
    crontab <(
        crontab -l 2>/dev/null | grep -v "${0##*/}"
        echo '*/'${3:-"30"}' * * * * DISPLAY=:0.0 '"$(cd ${0%/*}; pwd)/${0##*/}"' '$1 ' >/dev/null'
        )
    crontab -l
else
    last=/var/tmp/${0##*/}.last
    feh --bg-fill $(find $1 -type f ! -wholename "$(cat $last 2>/dev/null)" -print | shuf -n1 | tee $last)
fi
