#!/bin/bash

for n in ${@-$(cat)}; do
    tmux ${cmd-new}-window ${cmd+-d -v} -P -F "Opening: ${n}" "ssh -tYq ${n}"
    : ${cmd:=split}
    tmux select-layout tiled >/dev/null
done

tmux set-window-option synchronize-panes on >/dev/null
