#!/bin/sh

xterminal="${1:-$(get-terminal)}"

tmux list-sessions | awk -F: '$NF !~ /attached/ { print $1 }' | while read s; do
    ${xterminal} -e tmux attach-session -t ${s} &>/dev/null &
done
disown -a
