#!/bin/sh

[ $# -gt 0 ] && xterminal="$1" || xterminal=`get-terminal`

for s in $(tmux list-sessions | awk -F: '$NF !~ /attached/ { print $1 }'); do
    ${xterminal} -e tmux attach-session -t $s &>/dev/null &
done
disown -a
